config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tasks, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :resource_name, :resource, :devise_mapping, :resource_class
def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def resource_class
  User
end

def devise_mapping
  @devise_mapping ||= Devise.mappings[:user]
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save 
      respond_to do |format|
      format.html {redirect_to root_path flash[:notice] = "Task created"}
      format.js { }
    end
    else
      respond_to do |format|
      format.html {redirect_to root_path flash[:notice] = "Please try again"}
      format.js { }
    end
    end

    
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
    flash[:notice] = "Task edited"
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_modals.html.erb
<div class="popup-content" >
      <h2>Log in</h2>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>

      <div class="actions">
        <%= f.submit "Log in" %>
      </div>
    <% end %>

    <%= render "devise/shared/links" %>
</div>

<div class="popup-signup">
  <h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>
</div>

app/views/home/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'layouts/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>

  <li class="category-title" style="cursor: pointer;"><%= category.title  %></li>
  <div class="card">
    <ul id="<%=category.title%>">
      <% category.tasks.each do |task|  %>
      <li>
        <%= task.title  %>
        <% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D')  %>
        <% end %>
        <i class="fa fa-trash-o"></i>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  </ul>
</div>



<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= render 'modals' %>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      
      
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      
    </ul>
    <div class="avatar">
      <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
    </div>
        
      <div class="dropdown-content" style="position: absolute;top:50px;right: 10px;box-shadow: 0px 0px 2px">
        <ul style="list-style-type: none;text-align: center;">
        <% unless user_signed_in? %>
      <li class="nav-item" id = "login">
        <%= link_to "Log in", "#", class: "nav-link" %>
      </li>
      <li class="nav-item" id = "signup">
        <%= link_to "Sign up", "#", class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      </ul>
      </div>

  </div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
<style type="text/css">
  /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.popup-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 40%; /* Could be more or less, depending on screen size */
  position: absolute; top: 10%; left: 30%;

}

.popup-signup {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 40%; /* Could be more or less, depending on screen size */
  position: absolute; top: 10%; left: 30%;

}
/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}
</style>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<li>
    <%= task.title  %>
    <% unless task.deadline.nil? %>
    , to read: <%= task.deadline.strftime('%D')  %>
    <% end %>
</li>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/create.js.erb
alert("le fichier JS est exécuté!");
document.getElementById("<%=@category.title%>").insertAdjacentHTML("beforeend", "<%= j render 'task', task: @task %>")

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>	
<%= form_tag(task_path, method: "put") do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>

<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>